// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgAddAccountAuth } from "./types/sao/did/tx";
import { MsgUpdateAccountAuths } from "./types/sao/did/tx";
import { MsgResetStore } from "./types/sao/did/tx";
import { MsgAddPastSeed } from "./types/sao/did/tx";
import { MsgUnbinding } from "./types/sao/did/tx";
import { MsgAddBinding } from "./types/sao/did/tx";
import { MsgCleanupSidDocuments } from "./types/sao/did/tx";
import { MsgUpdateSidDocument } from "./types/sao/did/tx";
import { MsgCleanupPastSeeds } from "./types/sao/did/tx";


export { MsgAddAccountAuth, MsgUpdateAccountAuths, MsgResetStore, MsgAddPastSeed, MsgUnbinding, MsgAddBinding, MsgCleanupSidDocuments, MsgUpdateSidDocument, MsgCleanupPastSeeds };

type sendMsgAddAccountAuthParams = {
  value: MsgAddAccountAuth,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateAccountAuthsParams = {
  value: MsgUpdateAccountAuths,
  fee?: StdFee,
  memo?: string
};

type sendMsgResetStoreParams = {
  value: MsgResetStore,
  fee?: StdFee,
  memo?: string
};

type sendMsgAddPastSeedParams = {
  value: MsgAddPastSeed,
  fee?: StdFee,
  memo?: string
};

type sendMsgUnbindingParams = {
  value: MsgUnbinding,
  fee?: StdFee,
  memo?: string
};

type sendMsgAddBindingParams = {
  value: MsgAddBinding,
  fee?: StdFee,
  memo?: string
};

type sendMsgCleanupSidDocumentsParams = {
  value: MsgCleanupSidDocuments,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateSidDocumentParams = {
  value: MsgUpdateSidDocument,
  fee?: StdFee,
  memo?: string
};

type sendMsgCleanupPastSeedsParams = {
  value: MsgCleanupPastSeeds,
  fee?: StdFee,
  memo?: string
};


type msgAddAccountAuthParams = {
  value: MsgAddAccountAuth,
};

type msgUpdateAccountAuthsParams = {
  value: MsgUpdateAccountAuths,
};

type msgResetStoreParams = {
  value: MsgResetStore,
};

type msgAddPastSeedParams = {
  value: MsgAddPastSeed,
};

type msgUnbindingParams = {
  value: MsgUnbinding,
};

type msgAddBindingParams = {
  value: MsgAddBinding,
};

type msgCleanupSidDocumentsParams = {
  value: MsgCleanupSidDocuments,
};

type msgUpdateSidDocumentParams = {
  value: MsgUpdateSidDocument,
};

type msgCleanupPastSeedsParams = {
  value: MsgCleanupPastSeeds,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgAddAccountAuth({ value, fee, memo }: sendMsgAddAccountAuthParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAddAccountAuth: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgAddAccountAuth({ value: MsgAddAccountAuth.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAddAccountAuth: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateAccountAuths({ value, fee, memo }: sendMsgUpdateAccountAuthsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateAccountAuths: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdateAccountAuths({ value: MsgUpdateAccountAuths.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateAccountAuths: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgResetStore({ value, fee, memo }: sendMsgResetStoreParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgResetStore: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgResetStore({ value: MsgResetStore.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgResetStore: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgAddPastSeed({ value, fee, memo }: sendMsgAddPastSeedParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAddPastSeed: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgAddPastSeed({ value: MsgAddPastSeed.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAddPastSeed: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUnbinding({ value, fee, memo }: sendMsgUnbindingParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUnbinding: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUnbinding({ value: MsgUnbinding.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUnbinding: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgAddBinding({ value, fee, memo }: sendMsgAddBindingParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAddBinding: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgAddBinding({ value: MsgAddBinding.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAddBinding: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCleanupSidDocuments({ value, fee, memo }: sendMsgCleanupSidDocumentsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCleanupSidDocuments: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCleanupSidDocuments({ value: MsgCleanupSidDocuments.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCleanupSidDocuments: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateSidDocument({ value, fee, memo }: sendMsgUpdateSidDocumentParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateSidDocument: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdateSidDocument({ value: MsgUpdateSidDocument.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateSidDocument: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCleanupPastSeeds({ value, fee, memo }: sendMsgCleanupPastSeedsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCleanupPastSeeds: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCleanupPastSeeds({ value: MsgCleanupPastSeeds.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCleanupPastSeeds: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgAddAccountAuth({ value }: msgAddAccountAuthParams): EncodeObject {
			try {
				return { typeUrl: "/saonetwork.sao.did.MsgAddAccountAuth", value: MsgAddAccountAuth.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAddAccountAuth: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateAccountAuths({ value }: msgUpdateAccountAuthsParams): EncodeObject {
			try {
				return { typeUrl: "/saonetwork.sao.did.MsgUpdateAccountAuths", value: MsgUpdateAccountAuths.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateAccountAuths: Could not create message: ' + e.message)
			}
		},
		
		msgResetStore({ value }: msgResetStoreParams): EncodeObject {
			try {
				return { typeUrl: "/saonetwork.sao.did.MsgResetStore", value: MsgResetStore.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgResetStore: Could not create message: ' + e.message)
			}
		},
		
		msgAddPastSeed({ value }: msgAddPastSeedParams): EncodeObject {
			try {
				return { typeUrl: "/saonetwork.sao.did.MsgAddPastSeed", value: MsgAddPastSeed.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAddPastSeed: Could not create message: ' + e.message)
			}
		},
		
		msgUnbinding({ value }: msgUnbindingParams): EncodeObject {
			try {
				return { typeUrl: "/saonetwork.sao.did.MsgUnbinding", value: MsgUnbinding.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUnbinding: Could not create message: ' + e.message)
			}
		},
		
		msgAddBinding({ value }: msgAddBindingParams): EncodeObject {
			try {
				return { typeUrl: "/saonetwork.sao.did.MsgAddBinding", value: MsgAddBinding.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAddBinding: Could not create message: ' + e.message)
			}
		},
		
		msgCleanupSidDocuments({ value }: msgCleanupSidDocumentsParams): EncodeObject {
			try {
				return { typeUrl: "/saonetwork.sao.did.MsgCleanupSidDocuments", value: MsgCleanupSidDocuments.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCleanupSidDocuments: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateSidDocument({ value }: msgUpdateSidDocumentParams): EncodeObject {
			try {
				return { typeUrl: "/saonetwork.sao.did.MsgUpdateSidDocument", value: MsgUpdateSidDocument.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateSidDocument: Could not create message: ' + e.message)
			}
		},
		
		msgCleanupPastSeeds({ value }: msgCleanupPastSeedsParams): EncodeObject {
			try {
				return { typeUrl: "/saonetwork.sao.did.MsgCleanupPastSeeds", value: MsgCleanupPastSeeds.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCleanupPastSeeds: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			SaonetworkSaoDid: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;